language: javascript
node_js:
  - "8"
before_install:
  - openssl aes-256-cbc -K $encrypted_d89376f3278d_key -iv $encrypted_d89376f3278d_iv
    -in id_rsa.enc -out ~/.ssh/id_rsa -d
  - chmod 600 ~/.ssh/id_rsa
install:
  npm install
script:
  scp index.html root@47.105.54.250:www
#after_script:
  #scp index.html root@47.105.54.250/www


